[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "discord-py",
    "pystyle>=2.9",
    "python-dotenv",
    "requests>=2.32.3",
]
